name: Build LaTeX document
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: v1/english
        pre_compile: |
          rm -f v1/english/whitepaper.pdf
        post_compile: |
          mv main.pdf whitepaper.pdf

    - name: Verify PDF file
      run: |
        if [ ! -f "v1/english/whitepaper.pdf" ]; then echo "PDF not found!"; exit 1; fi

    - name: Bump version and push tag
      id: bump_version
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        INITIAL_VERSION: 1.5.0

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump_version.outputs.new_tag }}
        release_name: ${{ steps.bump_version.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: v1/english/whitepaper.pdf
        asset_name: whitepaper.pdf
        asset_content_type: application/pdf
